= spring-boot-bare

A minimal command line Spring Boot app.


== Building behind a proxy env

----
mvn compile
mvn spring-boot:run
----

NOTE: If you behind a proxy, the maven pom's parent dependency might fail to download. In this case
try moving it to dependencies section as workaround, and then reset pom again to rerun.
----
        <!-- Workaround to fetch the dependency first -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-parent</artifactId>
            <version>1.4.1.RELEASE</version>
            <type>pom</type>
        </dependency>
----


== How to use Mave exec plugin with spring-boot

Due to usage of spring-boot-starter-parent in pom.xml, we can simply run
 mvn exec:java -Dexec.mainClass=zemian.spring.boot.Hello

Because the exec-maven-plugin is preconfigured! However spring-boot let you redefine
another property like this.
 mvn exec:java -Dstart-class=zemian.spring.boot.hello.Hello
 
 
== How to run built-in SpringApplication with maven
 mvn exec:java -Dstart-class=org.springframework.boot.SpringApplication -Dexec.args="--spring.main.sources=zemian.spring.boot.hello.Hello"

Or you can use system props
 mvn exec:java -Dstart-class=org.springframework.boot.SpringApplication -Dspring.main.sources=zemian.spring.boot.hello.Hello
